### ISSUE TITLE
Update URL in client with fragment identifiers for state

### ISSUE THREAD

**Issue by ekansa** [periodo/periodo-client#110] opened 2016-04-27 17:33 UTC
One improvement that can be useful would be to express the current state of the PeriodO client (collections being filtered, text string matches, geographic coverage selected, etc.) in the URL, using javascript to update the fragment identifier.

The purpose of this improvement would be to allow people to link directly to a filtered view of the PeriodO Client.

**Comment by rybesh** [comment] 2016-04-27 18:05
Yep, definitely. One of the things we ran out of time to do in the first phase…

**Comment by atomrab** [comment] 2016-04-27 18:51
We may want to consider ways to assign URIs to user-defined collections, as
well -- I just had an email exchange with Brad Hafford at the Ur
Digitization project, who wanted to use PeriodO URIs but didn't want to
commit to any particular set of dates. I pointed him to the Getty AAT for
concept URIs, but suggested that he could attach Woolley's definitions to
Woolley's own usage in the documentation. I think he would have been happy
to see a URI that pointed to "six definitions for Ubaid in the area
covering what is now southern Iraq".

**Comment by rybesh** [comment] 2017-05-12 17:16
Duplicate of #76

**Closed by rybesh** 2017-05-12 17:16 UTC
