### ISSUE TITLE
Patch review page can get stale mergeURL value (because GetPatchRequest is not dispatched)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#303] opened 2020-12-08 14:16 UTC
I've been having this problem with Chrome (Mac OS 10.12.6, Chrome Version 87.0.4280.67 (Official Build) (x86_64)) for a while, but don't want to try to deal with it by clearing the cache, since I have some local collections I haven't gotten around to backing up. I can log in normally with my ORCID, but this is all I see on the review patches screen: 

![image](https://user-images.githubusercontent.com/4740995/101494819-6bcf6e80-392d-11eb-9fb7-dbee9f24ace5.png)

I do not have the same problem on Firefox.

**Comment by atomrab** [comment] 2020-12-08 14:17
I also appear as logged in on the settings page, but when I reload the review page, it doesn't recognize me as logged in.

**Comment by atomrab** [comment] 2020-12-08 14:33
"Accept changes?" module appears in Chrome incognito window, but same error as in #304 appears when I attempt to accept the changes.

**Comment by rybesh** [comment] 2020-12-08 16:15
What do you see when you go to this page?

https://client.perio.do/?page=backend-edit&backendID=web-https%3A%2F%2Fdata.perio.do%2F

**Comment by rybesh** [comment] 2020-12-08 16:18
Ah, I see now you said the settings page shows you as logged in. Try clicking the "sign out" link, then signing in again.

**Comment by rybesh** [comment] 2020-12-08 16:25
Note that you can only be logged in to PeriodO from one browser at a time. When you log in, a token is stored in your browser. Logging in from another browser invalidates that token, and creates a new token which is stored in the 2nd browser. If you then go back to the 1st browser, it will think it is logged in (because it has a token) but attempts to submit or accept changes will fail (because the token is no longer valid). Signing out and signing in again should give you a new valid token.

I'm not entirely sure why the settings page shows you as logged in, though, I will have to look into that.

**Comment by rybesh** [comment] 2020-12-08 16:33
If I log into Chrome and go to the review changes page, then log in from another browser, and then go back to the settings page in Chrome, it correctly shows me as logged out. So I'm not entirely sure what's going on here. It would be helpful to watch you do this over Zoom with the Chrome developer tools open.

**Comment by rybesh** [comment] 2020-12-08 18:41
OK, I think I see what the issue is. It's possible to

1. visit the patch review page
1. leave the page (i.e. to go to the backend settings page)
1. logged-in status changes (i.e. sign in or sign out)
1. return to patch review page, but it now has a stale `mergeURL` value because `GetPatchRequest` is not dispatched again when the patch review page is visited the 2nd time.

As a result one can be logged-in and not see the `Accept changes?` form (because `mergeURL` has a stale `null` value), or one can be logged-out and see the `Accept changes?` form (which will fail if used, because `mergeURL` has a stale non-`null` value).

**Comment by rybesh** [comment] 2020-12-08 18:51
Workaround for now when you're getting this problem: do a `Force Reload This Page` (⇧⌘R on macOS) on the patch review page, and it should correctly refresh the `mergeURL` and hence properly show/hide the `Accept changes?` form. Doing this will not affect your stored data, it just does a complete reload of the page.

**Comment by rybesh** [comment] 2020-12-09 14:19
Fixed by #305 and deployed to production.

**Closed** 2020-12-09 14:19 UTC
Labels: bug
