### ISSUE TITLE
Submission of new period failing

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#293] opened 2020-07-17 13:24 UTC
Via Ceri Binding:

> I've been trying to add a single period into an existing authority (ARIADNE Data Collection 2015), that was omitted from the original submission. Using the 'new' client I've got as far as importing that authority to an in-browser data source, created the new period, selected it from the list of changes and attempted to submit to the canonical dataset - but it's displaying an error, see attached screen shot. Is there something obvious that I'm doing wrong here? Also attached the resultant patch file in case it gives further clues.

![periodo-submission-error](https://user-images.githubusercontent.com/84592/87790880-48d1e000-c80f-11ea-9514-6e0e04438556.png)

[patch (5)-1.jsonpatch.zip](https://github.com/periodo/periodo-client/files/4938053/patch.5.-1.jsonpatch.zip)

**Comment by rybesh** [comment] 2020-07-17 13:26
@ptgolden Looks like maybe a dataset with inline context is being compared to one without inline context?

**Comment by rybesh** [comment] 2020-07-17 13:35
I fixed and re-submitted the broken patch:

https://client.perio.do/?page=review-patch&backendID=web-https%3A%2F%2Fdata.perio.do%2F&patchURL=patches%2F266%2F

**Comment by rybesh** [comment] 2020-07-17 13:38
Here's the disturbing bits of the patch:

```json
[
  {
    "op": "remove",
    "path": "/primaryTopicOf"
  },
  …snipped…
  {
    "op": "remove",
    "path": "/@context"
  },
  {
    "op": "remove",
    "path": "/id"
  }
]
```

**Comment by atomrab** [comment] 2020-07-17 15:29
Do you want me to try to resubmit the Priestley updates, which may fall into the same category -- that is, a local idb containing a downloaded existing authority, with additions, started before the new client was implemented, but submitted with the new patch pipeline? Maybe the issue is that the validation/reduplication prevention tools that were implemented are conflicting with the old import/update/submit workflow?

**Comment by ptgolden** [comment] 2020-07-17 16:05
This is definitely an issue with the new technique of generating diffs-- I will investigate after lunch

**Comment by atomrab** [comment] 2020-07-17 16:09
I went ahead to test this with Priestley, and yes, I get the same result:

![image](https://user-images.githubusercontent.com/4740995/87807588-09f75680-c81e-11ea-9b82-30f0960e3573.png)

**Comment by ptgolden** [comment] 2020-07-17 16:32
Yeah, I think I see what's happening

**Comment by ptgolden** [comment] 2020-07-17 20:50
This should be fixed by be242c10f99198289d5bf0f5cf01ddfd74929c0c

**Comment by atomrab** [comment] 2020-07-17 21:58
Do you want me to test it?

**Comment by rybesh** [comment] 2020-07-17 22:48
Go for it; the fix has been deployed to client.perio.do

**Comment by ptgolden** [comment] 2020-07-21 02:29
Closing because this particular problem with submissions is fixed.

**Closed by ptgolden** 2020-07-21 02:29 UTC
